[workspace]
authors = ["tdehoff <tatianadehoff@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoBLAS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.5.0,<26"
